version: 2.1
orbs:
  deploy: lucos/deploy@dev:alpha
jobs:
  build:
    parameters:
      architecture:
        type: string
    environment:
      ARCH: << parameters.architecture >>
    docker:
      - image: circleci/buildpack-deps:buster
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker-compose build
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            docker-compose push
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          name: amd64-build
          context: docker
          architecture: amd64
      - deploy/remote-build:
          name: arm-build
          context: docker
          build-domain: xwing.s.l42.eu
          ssh-port: 2222
          architecture: arm
      - deploy/deploy-valen:
          requires:
            - amd64-build
          filters:
            branches:
              only:
                - main
      - deploy/deploy:
          name: deploy-pi
          context: docker
          host-domain: xwing.s.l42.eu
          architecture: arm
          requires:
            - arm-build
          filters:
            branches:
              only:
                - main